code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 
code --install-extension 