#!/bin/sh

# Ask for the administrator password upfront
sudo -v

###############################################################################
# Homebrew                                                                    #
###############################################################################

echo 'Installing Homebrew and getting all the MacOS packages...'

# Check for Homebrew and install it if missing
if test ! $(which brew)
then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade --all

brew tap homebrew/bundle
brew bundle --global

brew cleanup

###############################################################################
# Shell                                                                       #
###############################################################################

echo 'Setting up your zsh shell...'
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# Make ZSH the default shell environment
chsh -s $(which zsh)

###############################################################################
# Keyboard                                                                    #
###############################################################################

echo 'Setting up your custom keyboard config...'
zsh ./karabiner

###############################################################################
# Editors                                                                     #
###############################################################################
echo 'Setting up your Editors packages...'
zsh ./vscode

###############################################################################
# Symlinks to link dotfiles into ~/                                           #
###############################################################################

echo 'Symlinking all your dotfiles...'
zsh ./setup

###############################################################################
# Node Stuff                                                                  #
# https://github.com/hjuutilainen/dotfiles/blob/master/bin/osx-user-defaults.sh
###############################################################################

echo 'Setting up your Node packages...'
zsh ./node

###############################################################################
# OSX defaults                                                                #
# https://github.com/hjuutilainen/dotfiles/blob/master/bin/osx-user-defaults.sh
###############################################################################

echo 'Updating your MacOS default settings...'
zsh ./set-osx-defaults
